jobs:
  allow_failures:
    - os: windows
os:
  - osx
  - linux
  - windows
language: node_js
node_js:
  - node
  - 12
cache: cargo
before_install:
  # Install Rust and Cargo
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - sh /tmp/rustup.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then source "$HOME/.cargo/env"; fi
  # Set correct toolchain to allow Windows builds to pass
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then rustup toolchain default stable-x86_64-pc-windows-msvc; fi
  # Output the current toolchains to the log if on Windows for sanity checking
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then rustup toolchain list; fi
  # Install NPM packages
  - node -v
  - npm -v
  - npm install
script:
  - npm test
  # Publish when using '[publish binary]' keywords
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  # Excludes the bulky Rust target folder from the published build
  - rm -rf native/target
  - if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then npm run upload-binary || exit 0; fi;
